# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data Science Experts Group
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Data Scientists Network headquartered in Ottawa and spans data scientists and researchers across Canada
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://datascientistsnetwork2017.github.io/"
#url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username:
github_username:  datascientistsnetwork2017
disqus_username:

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: _sass
  style: compressed


images: '/images'
